distcc/distcc

README

Hello,
During `make install` the target `install_doc` complains about README missing, I looked around the issues and did not find something reported for this. The way I fixed it for now is by copying the README from the original svn repo: `https://distcc.googlecode.com/svn/trunk/README`. Let me know if that is ok with you?
Cheers
Amine

Adding missing README from svn to fix make install breakage

---

packaging/RedHat/conf/clients.allow

Recent RedHat-like distributions run distcc through systemd and
the configuration is not taken from this file, so add a comment that
put the poor user in the right direction.
This patch is RFC here because the downstream bug has not been
fixed and is going to be EOL'ed
See: https://bugzilla.redhat.com/show_bug.cgi?id=1187517
If this is not the way it should be fixed^Wworkarounded, please advise...

Add help for systemd-based RH-like distro users

---

src/hosts.c

#175 A bracket is not a part of an IPv6 address.

Fix the TCP host parsing of IPv6 address (#175)

---

man/distccd.1
src/dparent.c
src/zeroconf-reg.c
src/zeroconf.c
src/zeroconf.h

If server is started in zeroconf mode, the previous behavior was that the number of slots for any server was hardcoded to 4 * number of cpus.  This made zeroconf impracticle when different hosts had different core counts.
This commit allows distccd to be invoked in zeroconf mode with the -j parameter to specify total slots for the particular server being invoked.
If no -j specified, then this host will publish its total number of slots to be 2 * number of cores + 2.  (Note: this is the same behavior as when invoking a non-zerconf server without specifying -j.)
To maintain backward compatibily, if a distccd zeroconf server doesn't publish a value for slots, then it will be assigned a default total slots equal to the previous behavior of 4 * number of cores.
Note that the meaning of "slots" …

fix Issue #145. Allow -j (jobs) param to set number slots when used in zeroconf mode.

---

.travis.yml
README.md

These changes add a .travis.yml file to the root directory of the project.  With this in place it would be possible for an administrator to start a travis-ci.org build for the project to cover a Debian/Ubuntu native build.  The service is free for Open Source projects. 
As I am not very good at using GitHub there is also ee86ccf on the end.  This updates the web documentation link as suggested by @n1tehawk under #157

Add tracis-ci.org Build To distcc Project

---

include_server/parse_command.py

These arguments are used by clang but until now, unrecognized by distcc.

Handle arguments needed to build Swift on MacOS

---

README

The README text file had the old Google Code project link in it.  This project migrated to GitHub following the closure of the Google Code services.

Correct Code Link In README

---

src/stats.c

Adding a comment should be enough to avoid GCC 7 error on fallthrough in switch statement. Alternatively one can use C++17 attribute which is available in C++11 and C++15 under `gnu::` or in general GNU attribute syntax.

Add fallthrough comment to avoid GCC 7 error

---

configure.ac
src/access.c
src/clinet.c
src/exec.c
src/lsdistcc.c
src/rslave.c
src/serve.c
src/zeroconf.c

Only the first commit is strictly necessary; the other commits fix compilation with -Werror. (musl warns when <sys/poll.h> or <sys/signal.h> is used.)

Fix compilation with musl libc

---

.gitignore
.travis.yml
configure.ac
docker/README.md
docker/base/Dockerfile
docker/base/apt-conf
docker/build.sh
docker/compilers/Dockerfile.clang-3.8
docker/compilers/Dockerfile.gcc-4.8
docker/compilers/Dockerfile.gcc-5
test/testdistcc.py

This is an attempt to extend the Travis CI configuration for building distcc on macOS using Clang. In order to get it working I needed to adjust as well some tests to cope with clang as well.
Apart from that I have created as well some Dockerfile's to easily run builds in an isolated environment (also nice for macOS users)

Extend Travis CI configuration for macOS/clang

---

src/serve.c

Sometimes on a busy server, you will get errors reading stdout/stderr.
If we send out DOTO 0 without SERR/SOUT, we get a protocol derailment.
It is better to avoid sending DOTO 0 in those cases, so that we get a
better error report on the client and avoid a "scary" warning message.
- This program is free software; you can redistribute it and/or
- modify it under the terms of the GNU General Public License
- as published by the Free Software Foundation; either version 2
- of the License, or (at your option) any later version.
*
- This program is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- GNU General Public License for more details.

Avoid protocol derailment for errors

---

configure.ac

The "if mmap() supports MAP_FAILED" test in configure.ac didn't include <stddef.h> leaving NULL undeclared on most modern (at least the ones I tested) C compilers, and therefore the test always failing.

FIX: NULL is undeclared without stddef.h so the MAP_FAILED test fails

---

INSTALL
configure.ac
src/auth_distcc.c
src/zeroconf-reg.c
src/zeroconf.c

These pedantic fixes and configure-variants extensions were required for compilation on OpenIndiana Hipster. Verified that build succeeds on Debian 8 with these in place.

Portability fixes for distcc

---

src/compile.c
src/exec.c
src/lsdistcc.c

On OpenBSD, time_t is defined as a 64-bit type. So adjust the format string accordingly and make sure this gets casted correctly for other systems too.

Handle 64-bit time_t on OpenBSD

---

src/zeroconf.c

This pull request fixes an issue when calling distcc with zeroconf from ninja. Closing all open file descriptors in the zeroconf daemon fixes a bug where ninja was waiting for the daemon to time out (~25 seconds) for each compile.

Close all file descriptors in zeroconf daemon process

---

INSTALL
Makefile.in
man/distcc.1
man/distccd.1
src/daemon.c
src/dopt.c
src/dopt.h
src/serve.c
test/testdistcc.py
update-distcc-symlinks.py

fixes the very old CVE-2004-2687 https://github.com/distcc/distcc/issues/155
at least unless gcc or clang can be exploited into executing arbitrary code--
but that is much more difficult than the current exploit.
(C++ templates are turing complete [1]....)
[1] http://web.archive.org/web/20131101122512/http://ubietylab.net/ubigraph/content/Papers/pdf/CppTuring.pdf
needs something like debian's update-distcc-symlinks script to maintain the whitelist. https://sources.debian.net/src/distcc/3.1-6.2/debian/update-distcc-symlinks.in/
What happens:
distcc check if a symlink to the binary exists in /usr/lib/distcc
if not, close the connection
This does not work with absolute pathnames to compilers.

access control on having masquerade set up for binary

---

man/distcc.1
src/compile.c
src/util.c
src/util.h

rewrites calls gcc to use fully qualified names
(like x86_64-linux-gnu-gcc), and fills in clang's -target option if it is not already filled in.

cross-compilation support

---

man/distcc.1
src/arg.c
src/compile.c
src/exitcode.h
src/where.c
src/where.h

Currently the --localslots are only read when distributing,
not when running locally.  Make sure to always parse the hosts
configuration, for localslots. We want to use --localslots_cpp
for running gcc -E, so use a special exit code to signal this.
- This program is free software; you can redistribute it and/or
- modify it under the terms of the GNU General Public License
- as published by the Free Software Foundation; either version 2
- of the License, or (at your option) any later version.
*
- This program is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- GNU General Public License for more details.

Localslots with gcc -E

---

src/serve.c

the not-very-used DISTCC_CMDLIST feature has its own whitelist.
Do not double-whitelist, which would be frustrating

serve: have DISTCC_CMDLIST feature turns off access

---

src/arg.c

This is insanity that there is no realloc in dcc_argv_append()

arg: allow for clang -target to be added.

---

src/compile.c

upgrade "Failed to distribute and no fallback" from warning to error

---

Makefile.in
man/distcc.1
src/daemon.c

You will need this, since `update-distcc-symlinks.py` is missing from the distribution tarball

Fix installation of update-distcc-symlinks

---

src/strip.c

The chromium build system (using clang) apparently concatenates
'-isystem' with path (i.e. uses it without space). Support stripping
this version as well to avoid the lot of warnings:
x86_64-pc-linux-gnu-clang++-6.0: warning: argument unused during compilation: '-isystem /usr/include/nss' [-Wunused-command-line-argument]

Strip compiler arguments starting with '-isystem'

---

Makefile.in
configure.ac
src/compile.c
src/daemon.c
src/dopt.c
src/serve.c
src/zeroconf-reg.c

This PR contains 5 improvements and fixes (in 6 distinctive commits):
- prevent a nullptr dereference if Avahi client creation fails
- support systems that don't have fstatat() and family; provide a fallback compiler whitelist check
that doesn't require faccesasat()
- the `--allow-private` option doesn't take an argument
- don't hardcode `/usr/lib/distcc` but `$PREFIX/distcc` instead
- fix  the QtCreator support workaround
The fstatat/faccessat chance was made in 2 commits; initially I thought it sufficient to skip the whitelisting feature on the concerned legacy systems but then I realised it was trivial to add an equivalent fallback implementation not using `faccessat()`. I didn't manage to squash the 2 commits without altering other commits.

Various patches mostly for cross-platform (Mac) support

---

man/distcc.1

Commit 6ef4e41 introduced DISTCC_IO_TIMEOUT, however, this was not
reflected in the TIMEOUTS section.

Fixed man page inconsistency - fix for issue #212

---

src/serve.c

compiler_masq: allow /usr/lib/distcc hardcoded

---

man/distccd.1
src/daemon.c
src/dopt.c
src/dopt.h
src/serve.c
src/ssh.c
test/testdistcc.py

As discussed in bug #155, --make-me-a-botnet was not self-descriptive enough.

global: add --enable-tcp-insecure in place of --make-me-a-botnet

---

src/util.c

This fixes building on FreeBSD.

Include netinet/in.h in src/util.c for sockaddr_in structure

---

src/arg.c

Relevant documentation:
https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
Also relevant is the need to avoid remote compilation when the compiler
might try to use a .gcda file generated locally during a profiling run
(common occurrence during profile-guided optimisation).

add some more GCC args that indicate profiling

---

AUTHORS

After being contacted by a user looking for Help, it was stated under #326 that Martin Pool thought it best that his email address be removed from the AUTHORS file.  Martin has not worked on distcc for over a decade, so is no longer in a position to provide much support to users.

Remove Martin Pool's Email Address From AUTHORS File

---

src/compile.c

Memory leak was detected by https://www.viva64.com/pvs-studio/
V773 The function was exited without releasing the 'newcmd' pointer.
A memory leak is possible.
Signed-off-by: Oleh Kravchenko <oleg@kaa.org.ua>

Fix possible memory leak

---

src/argutil.c
src/climasq.c
src/stringmap.c
src/util.c

- climasq.c:121 The function was exited without releasing the 'buf' pointer.
- argutil.c:109 The function was exited without releasing the 'b' pointer.
- stringmap.c:53 The function was exited without releasing the 'result' pointer.
- util.c:596 when realloc() fails in allocating memory,
original pointer 'loc' is lost.
Signed-off-by: Oleh Kravchenko <oleg@kaa.org.ua>

Fix memory leaks detected by PVS-Studio

---

include_server/parse_command.py
include_server/parse_command_test.py

The Linux kernel has started using statements like
-Wa,macros.s for including assembler with the code.
Handle these similar to the `-imacros` statement,
and send them to the compile server for processing.
Closes #312

Handle complex arguments, like assembler macros

---

doc/web/benchmark.html
doc/web/compared.html
doc/web/compilers.html
doc/web/distcc-lca-2004.html
doc/web/faq.html
doc/web/index.html
doc/web/man/distcc_1.html
doc/web/man/distccmon_text_1.html
doc/web/man/include_server_1.html
doc/web/results.html
doc/web/scenarios.html
doc/web/security.html
man/distcc.1
man/distccmon-text.1
man/include_server.1

ccache’s web site is now located at https://ccache.dev.

Update to new ccache URL

---

Makefile.in

pump support is the only thing (currently) that requires python support
in order to be built/tested. Don't predicate all testing on whether or
not PYTHON is available/specified.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>

Fix `make check` when pump support is not installed

---

Makefile.in

FreeBSD's copy of gzip (which originated from NetBSD) prints out a usage
message on stderr when `gzip --help` is invoked. Ergo, mute the noise from
`gzip --help` by redirecting stderr to stdout, which is redirected to
`/dev/null`.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>

Mute noise from `gzip --help`

---

Makefile.in

The FreeBSD ports system attempts to strip binaries installed with
`INSTALL_PROGRAM`, which unfortunately never works with scripts like
`pump`. Install `pump` with `INSTALL_SCRIPT` instead so the script is
installed with `install ..` instead of `install -s ..`.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>

Fix installing pump on FreeBSD with ports

---

Makefile.in

The install command doesn't use $(srcdir) so out-of-tree builds fail.
Signed-off-by: Ross Burton <ross.burton@intel.com>

Makefile.in: fix out-of-tree builds when the GNOME UI is enabled

---

src/compile.c

Currently when the client fails to connect to a server, it immediately goes to fallback and compiles locally. This causes problems for me when there are many servers and a couple are offline, as the client ends up compiling many files instead of just passing to other available servers. With this change, once all the hosts are attempted and found to be be "disliked", fallback still happens and localhost compiles, so it should not reduce robustness.

Try a new host after failing to connect instead of immediately falling back to localhost

---

src/access.c

Removed the flag that only allows numeric IP addresses for the allowed clients. DNS lookup will only be performed if configured with --enable-rfc2553.
DNS lookup only happens at daemon start.
Issue #366

Allow daemon DNS lookup of allowed hostnames

---

include_server/parse_file.py
include_server/statistics.py

.clock() got removed in python 3.8 and was marked as deprecated since 3.3
(https://github.com/python/cpython/pull/13270)
refers to https://github.com/distcc/distcc/issues/370

#370 Replace time.clock() with time.perf_counter()

---

.travis.yml

I think the thing that was happening is related to https://github.com/Homebrew/brew/issues/7360 and https://github.com/Homebrew/brew/issues/7356.
It'd be a shame if OSX builds started failing in a deeper way because of bit-rot while not testing on CI.

Bring back OSX to the test matrix

---

src/serve.c
test/testdistcc.py

Currently, distccd unconditionally adds `-MMD` to the compiler
invocation in pump mode. This leads to undesired behaviour if one
passes `-MD` to the compiler. For GCC, this leads to prefering `-MMD`,
which is more restrictive and might cause incorrect builds due to missed
system header dependensies. OTOH, Clang prefers `-MD`, which is safer
but emits the following warning:
```
clang-8: warning: argument unused during compilation: '-MMD' [-Wunused-command-line-argument]
```
The changes here fix this by only adding `-MMD` if neither `-MMD` nor
`-MD` is already present. Some exceptions in the tests, related to this bug,
are removed and the corresponding tests are now passing for Clang and
GCC.

Only add -MMD for pump mode if not present already

---

src/tempfile.c

src is in the include paths (the Makefile has -Isrc), and it contains
rpc.h, which collides with an internal header with the same name inside
/usr/include/w32api. This leads to compiler errors.
Fix by defining `WIN32_LEAN_AND_MEAN`, which prevents inclusion of rpc stuff.

tempfile: Fix build on Cygwin/MSYS2

---

src/compile.c

initialize memory before strcat to avoid heap overflow

---

configure.ac

This test produces errors on newer compilers (Xcode 12, probably others)  This means that it incorrectly fails, leading to
distcc trying to use its own `snprintf()`.  This then has compile issues with Xcode 12, breaking the build.
Fixes #397

Fix compile errors while detecting C99 snprintf

---

src/clirpc.c

Fix bug indicated by clang warning:
```
src/clirpc.c:126:9: warning: code will never be executed [-Wunreachable-code]
```
It looks like ~12 years ago someone added a log statement to this `if()` block while they had Python on their mind.  This means that the "expected version" check has been broken that entire time!

clirpc.c -- fix unreachable code

---

include_server/c_extensions/distcc_pump_c_extensions_module.c

```
include_server/c_extensions/distcc_pump_c_extensions_module.c: In function ‘XArgv’:
include_server/c_extensions/distcc_pump_c_extensions_module.c:214:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
214 |     argv[i] = PyUnicode_AsUTF8(string_object);    /* does not increase
|             ^
```
Far from optimal, but fixing const-correctness will require many changes.

Fix GCC warning

---

configure.ac
src/mon-gnome.c
src/renderer.c
src/renderer.h

GTK 2 has reached it's end of life: https://blog.gtk.org/2020/12/16/gtk-4-0/
So I thought this would be a good exercise for me to port this as I use distccmon-gnome from time to time and would like not to loose it. 
This should be ready to go and compiles without warnings for me.
Attached is a screenshot of both:

Port distccmon-gnome from gtk2 to gtk3

---

src/daemon.c
src/serve.c

distcc leaks memory and file descriptor during checks for the compiler whitelist.

Fix memory and file descriptor leaks

---

src/arg.c

When distcc is configured as the system compiler, sometimes it ends up being used on LTO builds. In this case it's faster to run the `cc` invocations locally, since most of the work of the compiler is done in the linker.
I'm guessing they'll be some discussion on this feature but I thought I'd rather post a patch.

Skip distributing LTO cc invocations

---

src/compile.c

On ALT Linux I've run into the following bug:
distcc gcc -Wall -std=gnu89 -I. -O2 -o hello.o -c hello.c
free(): invalid next size (fast)
Aborted (core dumped)
Apparently dcc_gcc_rewrite writes beyond the allocated memory:
valgrind --leak-check=full -v ./distcc gcc -Wall -std=gnu89 -I. -O2 -o hello.o -c hello.c
==11382== ERROR SUMMARY: 53 errors from 5 contexts (suppressed: 0 from 0)
==11382==
==11382== 1 errors in context 1 of 5:
==11382== Invalid write of size 1
==11382==    at 0x4C349D8: strcat (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11382==    by 0x10D165: dcc_gcc_rewrite_fqn (compile.c:611)
==11382==    by 0x10D4B4: dcc_build_somewhere (compile.c:725)
==11382==    by 0x10DC01: dcc_build_somewhere_timed (compile.c:1014)
==11382==    by 0x10E380: main (distcc.c:352) …

dcc_gcc_rewrite_fqn: avoid heap corruption

---

src/arg.c

This reverts commit 8dacd28d888210753e9457eb31175d8e2a1c348e.
The "LTO invocations are not worth distributing" statement is in general wrong.
GCC generates the (target) machine code for every compilation unit even with `-flto` (so it makes sense to distribute these). And the whole program analysis is not guaranteed to be the bottleneck of the build.
As a matter of fact distributing LTO compilations reduces the build time of LLVM/clang, GCC, and other programs (especially C++ ones).
Closes: #428

Revert "Skip distributing LTO cc invocations"

---

Makefile.in
update-distcc-symlinks.py

On ARM64 rpm-based distros GCC bits are installed into `/usr/lib64/gcc` and `/usr/libexec/gcc` directories. However `update-distcc-symlinks` does not scan these directories. As a result `update-distcc-symlinks` does NOT create symlinks to
* versioned GCC binaries (`gcc-8`, `gcc-10`, etc)
* fully qualified GCC binaries (`aarch64-linux-gnu-gcc-8`, etc)
With this patchset `update-distcc-symlinks` correctly work on such systems.
Also distcc/distccd always use `/usr/lib/distcc` (both on 32-bit and 64-bit hosts) so the masquerade mode always works as advertised in the manual:
```
PATH=/usr/lib/distcc:$PATH make -j32
```
Closes: #435

masquerade mode improvements for rpm-based systems

---

configure.ac
man/distccd.1
src/dopt.c
src/dopt.h
src/prefork.c
src/setuid.c

This new option sets `/proc/self/oom_score_adj` in prefork worker child processes. This can afford users a bit of protection against a scenario in which many concurrent compilation jobs cause an out-of-memory condition that prompts the kernel's OOM killer to kill a process that is not so "disposable" as a distccd worker.
This commit adds a new Autoconf test to check whether the host system type (that is, the type of the system on which the compiled binaries are to be run) is Linux. The new `--oom-score-adj` option is implemented only if the host system type is Linux.

distccd: add --oom-score-adj option (Linux only)

---

src/argutil.c
src/compile.c
src/distcc.h

With this patch I can cross-compile Linux kernel with clang and distcc.
Otherwise both remote compilation and local fallback fail like this:
```
cat > foo.c <<-EOF
int main(int argc, char **argv) { return 0; }
EOF
env DISTCC_HOSTS=127.0.0.1 distcc clang -c --target=aarch64-linux-gnu- foo.c
error: unknown target triple 'unknown', please use -triple or -arch
distcc[304773] ERROR: compile foo.c on 127.0.0.1 failed
distcc[304773] (dcc_build_somewhere) Warning: remote compilation of 'foo.c' failed, retrying locally
distcc[304773] Warning: failed to distribute foo.c to 127.0.0.1, running locally instead
error: unknown target triple 'unknown', please use -triple or -arch
distcc[304773] ERROR: compile foo.c on localhost failed
```
Linux' kernel makefiles specify the target arch with …

Improved cross-compilation with clang

---

src/backoff.c
src/compile.c
src/distcc.h

Since the commit a7dd5cf90e8c ("Try a new host after failing to connect instead of immediately falling back to localhost") distcc tries to choose a different host on connection/protocol errors. However when backoff is disabled (DISTCC_BACKOFF_PERIOD=0) distcc keeps retrying forever.
To avoid the problem limit the number of retries (currently to 3) when backoff is disabled.
Closes: #434

Restrict number of retries when backoff is disabled

---

doc/web/man/distccmon_text_1.html
man/distccmon-text.1
src/auth_distcc.c
src/auth_distccd.c

Found via `codespell -q 3 -S ./ChangeLog -L ake,ba,msdos,paralel,te`

Fix various source documentation typos

---

include_server/c_extensions/distcc_pump_c_extensions_module.c

Defining PY_SSIZE_T_CLEAN is required since python 3.10, and the types of length variables should be modified to match it. Otherwise functions like OsPathExists seem always return False in my tests.
The PY_SSIZE_T_CLEAN macro is supported at least back to python 3.5 according to docs.python.org, so I included it without any python version conditions.
This PR should fix https://github.com/distcc/distcc/issues/454 and likely https://github.com/distcc/distcc/issues/474 as well

Replace int with Py_ssize_t for distcc pump extension

---

man/distcc.1

The manual currently mentions the environment variable `DISTCC_NO_CROSS_REWRITE` https://github.com/distcc/distcc/blob/2d33649380fafbc278a274ec0339c211b83744cd/man/distcc.1#L779
However the environment variable that is actually checked is `DISTCC_NO_REWRITE_CROSS` https://github.com/distcc/distcc/blob/2d33649380fafbc278a274ec0339c211b83744cd/src/compile.c#L726
This was mentioned here <https://github.com/distcc/distcc/issues/412#issuecomment-895949625>, but no one seemed to have noticed (?)

Fix manual for DISTCC_NO_REWRITE_CROSS

---

include_server/setup.py

`distutils` has been deprecated for a long time (see PEP 632 [1]) and has been removed from Python 3.12. Thus include_server fails to build with Python 3.12. Use `setuptools` to avoid the problem.
[1] https://peps.python.org/pep-0632

include_server: use setuptools instead of distutils (for compatibility with Python >= 3.12)

---

src/compile.c
src/compile.h
src/remote.c

A preprocessed source with `.incbin` assembler directive can not be compiled remotely.
As a result of remote compilation failure distcc marks the build node as unreliable (for no good reason).
This increases the build time, especially when there are only a few (2 -- 3) build nodes.
With this patch distcc checks for the `.incbin` directive and compiles such files locally.
To save a bit of time the check is done only on compilation error.
Files with `.incbin` directives are very rare, about 1 per 10000
(in Linux kernel there might be a handful of them, depending on config).
On the other hand preprocessed C sources are rather long (several MB).
Scanning ~ 10000 such files might be slower than running an extra remote compilation.
Changes since v1:
- dcc_compile_remote: check for unsupported …

Compile files with .incbin assembler directive locally

---

src/access.c

`inet_from_inet6` returns a little endian representation of the address, which breaks the access control for IPv4 clients:
```
distccd[10488] (dcc_check_client) connection from ::ffff:10.64.MM.NN:36744
distccd[10488] (check_address_inet6) deny v6 client
distccd[10488] (check_address_inet6) deny v6 client
distccd[10488] (check_address_inet) deny client 0xa40MMNN, value 0x7f, mask 0xff
distccd[10488] (check_address_inet) deny client 0xa40MMNN, value 0x10ac, mask 0xf0ff
distccd[10488] (check_address_inet) deny client 0xa40MMNN, value 0xa, mask 0xff
distccd[10488] (check_address_inet) deny client 0xa40MMNN, value 0xa8c0, mask 0xffff
```
As a result clients connecting via IPv4 get (erroneously) rejected.
Use a simple(r) conversion method to avoid the problem.
Closes: #443

Fixed access control with IPv4-mapped addresses

---

INSTALL

When follow the INSTALL file to install distcc, make command will fail by:
ModuleNotFoundError: No module named 'setuptools'
make: *** [Makefile:586: include-server] Error 1
Which should since #493.

Add setuptools dependency

---

NEWS
src/stats.c
src/util.c
src/util.h

feat(stats): [Linux] Report `dcc_free_mem` from `/proc/meminfo`

---

include_server/parse_command.py

Syntax used had been deprecated for many python versions, at 3.12 the warning becomes an error and breaks the script.

Python 3.12 escaped characters update to parse_command.py

---

.github/workflows/c-build.yml

The old in-tree version seems to trip gcc errors. Probably there's not much point shipping a copy?

Install popt from OSes in CI

---

test/testdistcc.py

Currently, the Gdb tests fail in head in pump mode. The path seems to just not be there. I don't currently understand why, but it seems reasonably tolerable that users might have to set a source search path, so for now I'll just allow it.

Tests don't expect debug info to include full paths in pump mode
