distcc/distcc

- src/ssh.c
We have a large and ever-changing user community
to support and cannot rely on corporate to put ssh options
into the machine configurations. This allows us to place
-o ErrorLevel=ERROR in the DISTCC varable and have distcc
properly interpret that for passing on to execvp. Includes
changes from previous review by TafThorne
> ssh.c: tokenize the ssh command retrieved from DISTCC_SSH

- Makefile.in
- src/auth_common.c
> Fix building with auth (GSS-API)

- .travis.yml
Add missing dependencies, and run the ./configure && make check explicitly ("test" only makes the dir)
> Improve the Travis build script somewhat

- .travis.yml
see if this fixes the clang build
> fix the clang TravicCI

- src/arg.c
Includes objective-c and go support
> support some of gcc's most sensible -x options

- configure.ac
Amazingly this what the only patch require to build on temux---NATIVELY
https://github.com/termux
> Android support

- src/setuid.c
https://01.org/linuxgraphics/gfx-docs/drm/userspace-api/no_new_privs.html
> setuid: use PR_SET_NO_NEW_PRIVS on Linux

- src/distcc.c
Closes #218
I am just trusting #218
> Position of expandargv() in distcc.c

- src/zeroconf.c
Pull request as per https://github.com/distcc/distcc/commit/c8eac974fd3057bd8cff1a66898d1899f27bf998#commitcomment-28050670
> set jobs to n_cpus + 2, not 4 * n_cpus

- src/serve.c
> block unsafe compiler options

- src/daemon.c
- src/dparent.c
- src/dsignal.c
- src/trace.c
- src/trace.h
> fix race condition in signal handler

- man/distcc.1
- src/serve.c
- src/ssh.c
found while trying to fix ssh connections
> some misc fixes

- src/where.c
> Remove hardcoded limitation of 50 local/remote concurrent jobs

- .travis.yml
It seems to significantly speed up the build, dropping from around 30m to 3-4 (in line with linux)
> Run on an up-to-date OSX version

- src/argutil.c
- src/loadfile.c
These have been sitting in my local copy for quite some time now.
> Two small fixes

- doc/web/benchmark.html
- doc/web/faq.html
- doc/web/man/distcc_1.html
- doc/web/man/distccd_1.html
- doc/web/man/include_server_1.html
- include_server/c_extensions/distcc_pump_c_extensions_module.c
- include_server/cache_basics.py
- include_server/include_analyzer.py
- include_server/include_server.py
- include_server/macro_eval.py
- include_server/mirror_path_test.py
- include_server/setup.py
- include_server/test_data/distcc/src/distcc.h
- include_server/test_data/distcc/src/trace.h
- man/distccd.1
- packaging/RedHat/conf/clients.allow
- packaging/googlecode_upload.py
- popt/popt.h
- popt/poptparse.c
- src/arg.c
- src/serve.c
- src/snprintf.c
- test/testdistcc.py
Found via `codespell v2.1.dev0`
> Fix various typos

- src/mon-gnome.c
@shawnl Woops, there was a small debug print that I forgot to remove in my local rebase :S
Please review and merge this before tagging a new release :D
> Remove debug print that is no longer needed

- src/prefork.c
Observed behavior
-----------------
When compiling a big C project (Linux kernel) with distcc compilation nodes
never use 100% of CPU time, instead a system is 25 -- 40% idle (despite --jobs
is set to 3x the number of cores).
Analysis
--------
Linux kernel consists of many relatively small C sources and header files.
Compiling a single source file typically takes a fraction of a second (although
there are quite a number of "heavier" sources).
`dcc_preforked_child` exits after 50 requests. Thus a typical lifetime of
a worker process is just a few seconds. However `dcc_create_kids` sleeps for
a second after every fork. Also `dcc_preforked_child` sleeps for yet another second.
Which is >= 25% of a typical child lifetime. As a result distccd is unable to use
available CPU time (system load is …
> prefork: use available cores more efficiently

- Makefile.in
Solve the problem of failure to execute "make uninstall"
> fix: make uninstall failed

- src/dopt.c
> src/dopt.c: increase arg_max_jobs limit to max int

- src/util.c
Fixes #497: if the compiler is not found then distcc would segfault
Incorporates #500 plus some extra C string handling fixes.
Thanks to @georgefrancisco!
> Fix segfault in dcc_which

- .github/workflows/c-build.yml
> fix: disable macOS CI for now

- src/stats.c
- src/where.c
* Add void to dcc_stats_init()
* Add void to dcc_stats_init_kid()
* Add void to dcc_read_localslots_configuration()
> Add prototypes to function declaration
